'use client';
import Link from 'next/link';
import {CompleteWorkflowButton} from '../../LearningProgress';
import {useState} from 'react';
import {ArrowLeft,Check,Copy,Download,Play,Sparkles,Video} from 'lucide-react';

const characterPrompt="Create a professional, photorealistic multi-angle character reference sheet using the uploaded image(s) as the ONLY identity reference.\n\nIDENTITY: Preserve the exact person's facial structure, skin tone, hairstyle, age appearance, natural height, body proportions and distinctive features. Do not invent or beautify the face.\n\nWARDROBE: Reproduce the clothing, colours, patterns, logos, footwear and accessories shown in the uploaded reference images. If I specify a different outfit, apply only those requested clothing changes and keep the same person.\n\nREQUIRED VIEWS: Show a full-body front view, full-body back view, left profile, right profile, three-quarter view and detailed facial close-up. Keep the same character, outfit and body proportions in every panel.\n\nPRESENTATION: Arrange the views in a clean, clearly separated character-sheet layout on a plain neutral studio background, with even soft lighting, natural shadows, realistic skin and fabric textures and sharp details.\n\nCONSISTENCY: Maintain accurate front-to-back clothing details, hairline, facial features, body scale, hands, legs and footwear. No extra people, invented accessories, changed logos, warped anatomy, stylisation or identity drift. The finished sheet must be ready to use as a consistent character reference for AI video replacement.";

const genjutsuPrompt="Use the uploaded original 46-second dembow street-performance video as the primary reference for motion, performance, scene, lighting and camera work. Recreate the approximately 16-second matching excerpt shown in the AI example (not the full 46-second clip).\n\nReplace the designated central male performer with the supplied character-sheet identity. Maintain his exact facial identity, skin tone, close-cropped hair, natural height and body proportions. His clothing MUST remain identical in every shot: decorated olive military-style jacket with gold buttons, red-and-gold shoulder details, medals and dark leather strap, bright pink cartoon Powerpuff Girls shorts, blue-and-maroon FC Barcelona football socks and black combat boots.\n\nMatch the original performance timing, singing and dancing gestures, head turns, reactions, physical contact and interaction with the surrounding crowd. Preserve the source handheld camera movement, framing, perspective, cuts, foreground hands and phones, performance atmosphere, coloured stage/street lights, background, shadows and natural motion blur. Keep the replacement consistent in front, side, back and close-up views. Preserve source audio if supported, otherwise restore authorised audio in the editor and manually check lip sync.\n\nAim for natural live-action realism, physically plausible body and clothing motion, stable face and skin textures, accurate occlusion and synchronised performance. Avoid identity drift, morphing, artificial skin, duplicate characters, deformed hands, floating objects, changed wardrobe, camera redesign and lip-sync errors. Export a vertical 9:16 video.";

const originalVideo='https://d2ol7oe51mr4n9.cloudfront.net/user_3Fzv4wKUSDX4s66inQmCD1u4yFc/b5e27d9d-a109-4525-8306-ea3f70e4dcc9.mp4';
const aiVideo='https://d2ol7oe51mr4n9.cloudfront.net/user_3Fzv4wKUSDX4s66inQmCD1u4yFc/94c04cc0-e9f1-48cf-a4fd-a8c271ba069d.mp4';
const characterSheet='https://d2ol7oe51mr4n9.cloudfront.net/user_3Fzv4wKUSDX4s66inQmCD1u4yFc/06017105-11b5-47e6-aafd-f942478ead64.jpg';

function CopyPrompt({title,text}){const[copied,setCopied]=useState(false);async function copy(){await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1500)}return <article className="promptCard"><div><small>K4K PROMPT</small><h3>{title}</h3></div><pre>{text}</pre><button onClick={copy}><Copy/>{copied?'COPIED':'COPY PROMPT'}</button></article>}

export default function WorkflowOne(){return <main className="workflowPage">
<Link className="back" href="/academy"><ArrowLeft/> Back to Academy</Link>
<section className="workflowHero"><div className="kicker"><Sparkles/> K4K WORKFLOW 001</div><h1>DEMBOW PARTY CHARACTER SWAP<br/><i>ORIGINAL VS. AI.</i></h1><p>Watch the supplied 46-second dembow street-performance original and compare the 16-second AI recreation. Follow the exact character-sheet and motion-transfer workflow used for this example.</p><div className="workflowStats"><span><b>46s</b> original video</span><span><b>16s</b> AI result</span><span><b>9:16</b> vertical</span><span><b>1</b> character sheet</span></div></section>

<section className="lessonVideo" style={{display:"block"}}>
 <div style={{marginBottom:22}}><small style={{color:"#caff39",fontWeight:900,letterSpacing:2}}>WATCH BOTH VIDEOS · WORKFLOW 001</small><h2 style={{margin:"10px 0",fontSize:"clamp(24px,4vw,38px)"}}>ORIGINAL VIDEO <span style={{color:"#caff39"}}>VS.</span> AI RECREATION</h2><p style={{color:"#b9c7b4",lineHeight:1.7}}>These are the exact two videos supplied for this lesson. The AI result is a 16-second excerpt of the 46-second original, so compare the matching sequence rather than expecting equal durations.</p></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,280px),1fr))",gap:18}}>
  <article style={{border:"1px solid #ffffff29",borderRadius:14,overflow:"hidden",background:"#111711"}}>
   <div style={{padding:"14px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><strong style={{fontSize:13}}>01 · ORIGINAL REFERENCE</strong><span style={{fontSize:11,color:"#caff39"}}>46 SECONDS</span></div>
   <video controls playsInline preload="metadata" aria-label="Original reference video" style={{display:"block",width:"100%",maxHeight:460,background:"#000"}}><source src={originalVideo} type="video/mp4"/>Your browser does not support video.</video>
   <p style={{padding:"13px 16px",fontSize:12,lineHeight:1.6,color:"#b9c7b4",margin:0}}>Study the original actions, performance, environment and camera movement.</p>
  </article>
  <article style={{border:"1px solid #caff3955",borderRadius:14,overflow:"hidden",background:"#111711"}}>
   <div style={{padding:"14px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><strong style={{fontSize:13}}>02 · AI RECREATION</strong><span style={{fontSize:11,color:"#caff39"}}>16 SECONDS</span></div>
   <video controls playsInline preload="metadata" aria-label="AI recreation result video" style={{display:"block",width:"100%",maxHeight:460,background:"#000"}}><source src={aiVideo} type="video/mp4"/>Your browser does not support video.</video>
   <p style={{padding:"13px 16px",fontSize:12,lineHeight:1.6,color:"#b9c7b4",margin:0}}>Review the AI-generated result and compare it with the source clip.</p>
  </article>
 </div>
 </section>

<section className="resourceStrip"><div><small>REFERENCE ASSET</small><h2>Original reference video</h2><p>Download the supplied original video and select the corresponding 16-second sequence as your motion reference.</p></div><a href={originalVideo} download className="back"><Download/> DOWNLOAD REFERENCE VIDEO</a></section>

<section className="workflowBlock"><div className="stepNo">01</div><div><small>REFERENCE</small><h2>Find and upload your reference video</h2><p><b>What is a reference video?</b> It is the original clip whose movements, acting, camera angles and timing you want to recreate with your own characters.</p><ol><li>Open TikTok, Instagram Reels or YouTube Shorts and look for a short clip with clear characters and movements.</li><li>Choose a video you own or have permission to reuse. For this project, identify the approximately 16-second portion you want to recreate.</li><li>Save an authorised MP4 or MOV copy to your device. You can also use the downloadable practice video above.</li><li>Watch it carefully: identify who speaks, who moves, how the camera moves and which elements must remain unchanged.</li><li>When you reach Genjutsu in Step 03, upload this clip as the motion reference.</li></ol><p><b>K4K tip:</b> Clear faces, steady framing and simple actions make character replacement easier. Do not upload private or copyrighted videos without permission.</p></div></section>
<section className="workflowBlock"><div className="stepNo">02</div><div><small>02 · CHARACTER REFERENCE</small><h2>How your character must look</h2><p>This is an example of how your finished character sheet should look. Your own sheet should clearly show the same character from the front, back, both sides, a three-quarter angle and a detailed facial close-up. Keep their face, hairstyle, body proportions, outfit and accessories consistent in every view.</p><img src={characterSheet} alt="Example of how a consistent multi-angle character sheet should look" loading="lazy" style={{display:"block",width:"100%",maxWidth:940,borderRadius:12,margin:"18px 0",border:"1px solid #ffffff35"}}/><a href={characterSheet} target="_blank" rel="noopener noreferrer" download="k4k-workflow-01-character-sheet.jpg" className="back" style={{marginBottom:18}}><Download/> DOWNLOAD EXAMPLE CHARACTER SHEET</a><ol><li>Pick a sharp, well-lit portrait where the face is clearly visible.</li><li>For better results, prepare front, side and full-body reference views.</li><li>Keep your chosen character's face, hairstyle, body proportions, clothing, colours, footwear and accessories consistent in every view.</li><li>The image above is a visual example only. Upload your own character photo and copy the universal prompt below to generate your own character sheet.</li></ol><CopyPrompt title="Character Sheet Prompt" text={characterPrompt}/></div></section>
<section className="workflowBlock featuredStep"><div className="stepNo">03</div><div><small>HIGGSFIELD · GENJUTSU</small><h2>Genjutsu on Higgsfield — Motion Transfer setup</h2><p><b>Genjutsu is a tool inside Higgsfield.</b> Open Higgsfield, select <b>Genjutsu</b>, upload the reference video, add your character sheet, select <b>Motion Transfer</b>, paste the prompt below and generate.</p><div className="miniChecks"><span><Check/> Reference video</span><span><Check/> Character sheet</span><span><Check/> Motion Transfer</span><span><Check/> Prompt</span></div><CopyPrompt title="Genjutsu Character Replacement" text={genjutsuPrompt}/></div></section>
<section className="workflowBlock"><div className="stepNo">04</div><div><small>RESULT</small><h2>Watch and compare the AI result</h2><p>Check identity, hair, wardrobe, hands, background people, movement and camera behaviour. Regenerate problem areas instead of accepting the first output.</p><p><b>Compare the two videos at the top of this lesson:</b> play the original reference, then play the AI recreation. The AI output is 16 seconds and the full original is 46 seconds. Compare the matching portion, checking the face and outfit in every shot.</p></div></section>
<section className="workflowBlock"><div className="stepNo">05</div><div><small>EXPORT</small><h2>Finish and publish</h2><p>Trim, add licensed audio, colour-match where needed, apply subtle sharpening and export at 9:16, 1080 × 1920, 30fps for short-form platforms.</p></div></section>
<CompleteWorkflowButton lessonId="workflow-001"/>
</main>}