import Link from 'next/link';
import {ArrowLeft,ArrowRight,Check,Download,Play,Sparkles,Video} from 'lucide-react';

export default function WorkflowOne(){
return <main className="workflowPage">
<Link className="back" href="/academy"><ArrowLeft/> Back to Academy</Link>
<section className="workflowHero"><div className="kicker"><Sparkles/> K4K WORKFLOW 001</div><h1>RECREATE A VIRAL VIDEO<br/><i>WITH YOUR OWN CHARACTER.</i></h1><p>Reference video → character sheet → Genjutsu Motion Transfer → prompt → final AI result.</p><div className="workflowStats"><span><b>3.7M</b> views / 24h</span><span><b>241K</b> likes</span><span><b>73K</b> shares</span><span><b>14K</b> saves</span></div></section>
<section className="workflowBlock"><div className="stepNo">01</div><div><small>REFERENCE</small><h2>Choose the video you want to recreate</h2><p>Use the original as the motion and performance reference. Look for strong movement, camera energy, timing and reactions worth preserving.</p></div></section>
<section className="workflowBlock"><div className="stepNo">02</div><div><small>IDENTITY</small><h2>Choose your replacement character</h2><p>Use a clear photo of yourself, your own character or another image you are authorised to use. Front, profile, three-quarter and full-body references give the model more identity information.</p></div></section>
<section className="workflowBlock"><div className="stepNo">03</div><div><small>CHARACTER SHEET</small><h2>Lock the identity before generating</h2><p>Create a consistent sheet showing front, back, profile, three-quarter, full-body and close facial views. Keep face, hair, proportions, wardrobe and accessories consistent across every panel.</p></div></section>
<section className="workflowBlock featuredStep"><div className="stepNo">04</div><div><small>GENJUTSU WALKTHROUGH</small><h2>Follow the exact setup</h2><p>Open Higgsfield Genjutsu. Upload the original/reference video, add your character sheet, choose <b>Motion Transfer</b>, paste the K4K workflow prompt and generate.</p><div className="videoSlot"><Video/><div><b>STEP 4 VIDEO WALKTHROUGH</b><span>The Academy walkthrough video will play here.</span></div><Play/></div><div className="miniChecks"><span><Check/> Original video</span><span><Check/> Character sheet</span><span><Check/> Motion Transfer</span><span><Check/> K4K prompt</span></div></div></section>
<section className="workflowBlock"><div className="stepNo">05</div><div><small>PROMPT</small><h2>Use the reusable K4K workflow prompt</h2><p>The member prompt instructs the model to preserve the reference movement, timing, camera language, environment and background while keeping the supplied authorised character consistent throughout the sequence.</p></div></section>
<section className="workflowBlock"><div className="stepNo">06</div><div><small>AI RESULT</small><h2>Compare the generated result</h2><p>Check face consistency, hair, wardrobe, hands, background people, movement and camera behaviour before accepting the generation.</p><div className="videoSlot"><Play/><div><b>FINAL AI RESULT</b><span>The finished example video will play here.</span></div><ArrowRight/></div></div></section>
<section className="workflowBlock"><div className="stepNo">07</div><div><small>FINISH</small><h2>Edit, export and publish</h2><p>Trim the generation, add licensed audio, colour-match if needed, apply subtle sharpening and export at 9:16, 1080 × 1920, 30fps for short-form platforms.</p></div></section>
<section className="workflowDownloads"><div><small>MEMBER RESOURCES</small><h2>Everything for this workflow.</h2><p>The downloadable pack can include the written workflow, copy-ready prompt and authorised reference assets.</p></div><button disabled><Download/> Workflow PDF — coming next</button></section>
</main>}