'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Check,Copy as CopyIcon,Download,LockKeyhole,Play,Sparkles} from 'lucide-react';

const offers={GBP:{label:'£7.99',url:'https://buy.stripe.com/dRmbJ293u6d7egQ8CseEo0n'}};
const characterPrompt=`Using the uploaded person as the sole identity reference, create a professional character reference sheet while preserving facial structure, skin tone, hairstyle, body proportions and distinctive physical characteristics. Show consistent front, back, profile, three-quarter, full-body and close facial views. Maintain the same identity and wardrobe across every panel. Neutral studio background, even lighting and realistic proportions. Do not invent facial features or accessories.`;
const genjutsuPrompt=`Use the uploaded video as the primary motion, performance, composition and camera reference. Replace only the designated principal character with the person shown in the supplied character reference. Preserve facial identity, hairstyle, skin tone, body proportions and wardrobe consistently. Match the original movement, gestures, timing, orientation and interactions. Preserve handheld camera motion, framing, perspective, scene timing, environment, lighting and background people. Avoid identity drift, duplicate characters, warped hands, altered clothing or unnecessary camera changes.`;
const learningPillars=[{n:'01',title:'Study the reference',body:'Break down the action, camera movement, timing and creative hook before you generate.'},{n:'02',title:'Build the character',body:'Create consistent character references with reusable prompts and a repeatable method.'},{n:'03',title:'Direct with AI',body:'Use Genjutsu motion transfer, compare results and refine what matters.'}];
function useOffer(){return offers.GBP}
function Copy({title,text}){const[c,setC]=useState(false);return <article className="promptCard"><small>READY TO USE</small><h3>{title}</h3><pre>{text}</pre><button onClick={async()=>{await navigator.clipboard.writeText(text);setC(true);setTimeout(()=>setC(false),1400)}}><CopyIcon size={15}/>{c?'COPIED':'COPY PROMPT'}</button></article>}
export default function Home(){const o=useOffer();return <main className="launchPage">
<nav><a className="brand" href="#top"><span>K4K</span> ACADEMY</a><div style={{display:"flex",alignItems:"center",gap:22}}><a href="#method" className="loginLink">The Method</a><a className="loginLink" href="/login">Member Login</a></div></nav>
<section className="launchHero" id="top"><div className="eyebrow"><Sparkles size={14}/> DAILY AI TUTORIAL MEMBERSHIP</div><h1>WATCH IT.<br/><em>RECREATE IT.</em></h1><p>Learn the creative process behind AI video transformations. Study real examples, use practical prompts and develop a repeatable production workflow.</p><div className="launchPrice"><strong>{o.label}</strong><span>/ MONTH</span></div><a className="btn" href={o.url}>JOIN K4K ACADEMY <ArrowRight/></a><div className="micro"><span><Check/> Practical workflows</span><span><Check/> Copy-ready prompts</span><span><Check/> Guided learning</span></div></section>

<section id="method" style={{padding:'90px 5vw',background:'#0d110c',borderTop:'1px solid #ffffff18',borderBottom:'1px solid #ffffff18'}}><div style={{maxWidth:1200,margin:'0 auto'}}><div className="kicker">THE K4K METHOD</div><h2 style={{fontSize:'clamp(34px,5vw,64px)',letterSpacing:'-.045em',maxWidth:760,margin:'20px 0 35px'}}>FROM AN IDEA TO A FINISHED AI VIDEO.</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:16}}>{learningPillars.map(p=><article key={p.n} style={{border:'1px solid #ffffff22',borderRadius:14,padding:28,background:'#151a13'}}><span style={{color:'#caff39',fontWeight:800,letterSpacing:2}}>{p.n}</span><h3 style={{fontSize:23,margin:'22px 0 10px'}}>{p.title}</h3><p style={{lineHeight:1.65,color:'#b2b8ad',fontSize:14}}>{p.body}</p></article>)}</div></div></section>
<section className="homeCase"><div className="kicker">SEE WHAT YOU WILL LEARN</div><h2>FROM REFERENCE VIDEO TO <i>AI RECREATION.</i></h2><p className="caseLead">This is the reference video used for the featured K4K Academy lesson. Explore the creative breakdown, character setup and AI result in our featured lesson.</p><div style={{maxWidth:1200,margin:'30px auto 0'}}><img onError={e=>{e.currentTarget.style.display="none";e.currentTarget.nextElementSibling.style.display="block"}} src="/k4k-homepage-comparison.jpg" alt="K4K Academy original video compared with AI recreation, showing 3.8 million views, 244 thousand likes, 2,140 comments, 74 thousand shares and 14 thousand saves on the AI result only" style={{display:'block',width:'100%',height:'auto',borderRadius:18}}/><div style={{display:"none",padding:"75px 24px",textAlign:"center",border:"1px solid #ffffff22",borderRadius:18,background:"linear-gradient(120deg,#151a13,#241321)"}}><h3 style={{fontSize:"clamp(26px,4vw,46px)",margin:"0 0 14px"}}>ORIGINAL → AI RECREATION</h3><p style={{color:"#c4c8bf"}}>Explore the featured K4K transformation inside Workflow 001.</p><div style={{color:"#caff39",fontWeight:800}}>3.8M VIEWS · 244K LIKES · 74K SHARES</div></div><p style={{textAlign:'center',marginTop:18}}><a href="/academy/workflows/viral-character-swap" style={{color:'#caff39',fontWeight:700}}>Explore Workflow 001 →</a></p></div></section>
<section className="launchJoin"><div className="kicker">K4K ACADEMY</div><h2>ONE MEMBERSHIP.<br/><i>BUILD YOUR CREATIVE SKILLS.</i></h2><p>Guided lessons, ready-to-adapt prompts and practical AI creator workflows in one place.</p><div className="launchPrice"><strong>{o.label}</strong><span>/ MONTH</span></div><a className="btn" href={o.url}>START LEARNING <ArrowRight/></a><small><LockKeyhole/> Secure Stripe checkout. Checkout confirms the final amount and billing currency before payment.</small></section>
<footer><div className="brand"><span>K4K</span> ACADEMY</div><p>CREATE. DIRECT. EVOLVE.</p><div>© 2026 KREATIVE STUDIOS 4K</div></footer>
</main>}