'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Play,Check,Sparkles,Video,Layers3,WandSparkles,TrendingUp,Menu,X,LockKeyhole,Plus} from 'lucide-react';
const lessons=[['01','AI Creator Foundations','Build a repeatable creation system instead of chasing random tools.'],['02','Prompt Engineering','Write prompts that control identity, framing, lighting, movement and style.'],['03','Character Consistency','Create reference sheets and keep characters recognisable across scenes.'],['04','Cinematic AI Video','Turn still concepts into polished short-form video sequences.'],['05','Viral Storytelling','Hooks, pacing, reveals and formats engineered for retention.'],['06','Creator Monetisation','Package your skill for clients, collaborations and digital products.']];
const faqs=[['Is this a one-time course?','No. K4K Academy is an evolving membership. The library grows with new tutorials, prompts and workflows as the AI creator landscape changes.'],['Are the lessons live?','The core Academy is recorded and on-demand, so you can learn worldwide and at your own pace. Private 1:1 sessions are a separate premium service.'],['What do I get for £7.99/month?','Access to the lesson library, K4K Method, prompt drops, workflow breakdowns, new video aulas and future Academy updates while your membership is active.'],['Do I need experience?','No. The pathway starts with foundations and moves into advanced character, video, storytelling and monetisation workflows.'],['Can I cancel?','Yes. The membership is designed as a simple monthly subscription with no long-term commitment.']];
const offers={GBP:{label:'£7.99',url:'https://buy.stripe.com/dRmbJ293u6d7egQ8CseEo0n'},BRL:{label:'R$49,99',url:'https://buy.stripe.com/dRmbJ293u6d7egQ8CseEo0n'},USD:{label:'$9.99',url:'https://buy.stripe.com/dRmbJ293u6d7egQ8CseEo0n'},EUR:{label:'€8.99',url:'https://buy.stripe.com/dRmbJ293u6d7egQ8CseEo0n'}};
function useOffer(){const[o,setO]=useState(offers.USD);useEffect(()=>{fetch('/api/market').then(r=>r.json()).then(x=>setO(offers[x.currency]||offers.USD)).catch(()=>{})},[]);return o}
function CTA({small=false}){const o=useOffer();return <a className={small?'btn small':'btn'} href={o.url}>Join for {o.label} <ArrowRight size={small?15:18}/></a>}
function LocalPrice(){const o=useOffer();const p=o.label.match(/^([^0-9]*)(.*)$/);return <div className="price"><sup>{p?.[1]}</sup><strong>{p?.[2]}</strong><span>/ MONTH</span></div>}
export default function Home(){const[menu,setMenu]=useState(false);const[open,setOpen]=useState(0);return <main>
<nav><a className="brand" href="#top"><span>K4K</span> ACADEMY</a><div className="navlinks"><a href="#method">Method</a><a href="#library">Library</a><a href="#proof">Results</a><a href="#faq">FAQ</a></div><CTA small/><button className="menub" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>
{menu&&<div className="mobilemenu"><a onClick={()=>setMenu(false)} href="#method">Method</a><a onClick={()=>setMenu(false)} href="#library">Library</a><a onClick={()=>setMenu(false)} href="#proof">Results</a><a onClick={()=>setMenu(false)} href="#faq">FAQ</a><CTA/></div>}
<section className="hero" id="top"><div className="orb one"/><div className="eyebrow"><Sparkles size={14}/> THE CREATOR SYSTEM BEHIND KREATIVESTUDIOS4K</div><h1>DON'T JUST USE AI.<br/><em>DIRECT IT.</em></h1><p className="lead">Learn the exact creative systems behind cinematic AI content, consistent characters and viral short-form storytelling. New lessons. New prompts. Every month.</p><div className="heroactions"><CTA/><a className="watch" href="#showreel"><span><Play size={16} fill="currentColor"/></span> Watch the method</a></div><div className="micro"><span><Check/> Cancel anytime</span><span><Check/> Worldwide access</span><span><Check/> New content drops</span></div><div className="screen" id="showreel"><div className="screenbar"><span>THE K4K METHOD</span><span>00:47</span></div><div className="screenbody"><div className="playbig"><Play fill="currentColor"/></div><div className="screenwords"><small>FROM IDEA → EXECUTION</small><strong>CREATE WITHOUT LIMITS.</strong></div></div></div></section>
<section className="ticker"><div>AI VIDEO <b>✦</b> CHARACTER CONSISTENCY <b>✦</b> PROMPT ENGINEERING <b>✦</b> STORYTELLING <b>✦</b> MONETISATION <b>✦</b></div></section>
<section className="method" id="method"><div className="kicker">THE K4K METHOD</div><div className="split"><h2>A SYSTEM BUILT<br/>FOR <i>CREATORS.</i></h2><p>Not another collection of disconnected AI tutorials. K4K gives you a creative operating system: how to think, prompt, direct, refine and publish work that feels intentional.</p></div><div className="cards">{[[WandSparkles,'CONCEPT','Turn trends, ideas and references into a creative direction worth watching.'],[Layers3,'BUILD','Create characters, scenes and visual continuity with controlled workflows.'],[Video,'DIRECT','Control motion, camera language and pacing to make AI feel cinematic.'],[TrendingUp,'GROW','Package content for attention, audience growth, clients and monetisation.']].map(([Icon,t,p],i)=><article key={t}><Icon/><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
<section className="library" id="library"><div className="libraryhead"><div><div className="kicker">INSIDE THE ACADEMY</div><h2>YOUR CREATOR<br/><i>LIBRARY.</i></h2></div><p>Watch on demand. Apply immediately. Return whenever you need the workflow.</p></div><div className="lessonlist">{lessons.map((l,i)=><article key={l[0]}><div className="num">{l[0]}</div><div className="lessonicon">{i%2?<Layers3/>:<Play fill="currentColor"/>}</div><div><h3>{l[1]}</h3><p>{l[2]}</p></div><span className="duration">{8+i*3}–{15+i*3} MIN</span><ArrowRight className="arr"/></article>)}</div></section>
<section className="drops"><div className="dropvisual"><div className="promptwindow"><div className="dots">● ● ●</div><small>K4K / PROMPT DROP 024</small><p>“Create a cinematic character reference with controlled identity, natural skin texture, consistent proportions…”</p><span>NEW DROP</span></div></div><div className="dropcopy"><div className="kicker">ALWAYS EVOLVING</div><h2>NEW PROMPTS.<br/>NEW <i>WORKFLOWS.</i></h2><p>AI moves fast. Your Academy should too. Members receive new prompt systems, practical video lessons and workflow updates—not a course frozen in time.</p><div className="checkgrid">{['Prompt drops','Video aulas','Workflow updates','Creator strategies'].map(x=><span key={x}><Check/> {x}</span>)}</div></div></section>
<section className="proof" id="proof"><div className="kicker">PROOF, NOT THEORY</div><h2>BUILT FROM<br/><i>REAL ATTENTION.</i></h2><div className="stats"><div><strong>93.4M</strong><span>VIEWS</span></div><div><strong>14.1M</strong><span>VIEWERS</span></div><div><strong>1</strong><span>METHOD</span></div></div><p className="proofnote">Creator performance displayed by KreativeStudios4K. Results vary by creator, platform, execution and market.</p></section>
<section className="premium"><div><div className="kicker">NEED PERSONAL HELP?</div><h2>GO BEYOND<br/>THE <i>LIBRARY.</i></h2><p>Private 1:1 sessions are available separately for creators and businesses who want direct feedback, workflow troubleshooting or a personalised creative strategy.</p><a className="outline" href="mailto:hello@kreativestudios4k.com">Enquire about 1:1 <ArrowRight/></a></div><div className="mentor"><span>PRIVATE</span><strong>1:1</strong><small>CREATOR SESSION</small></div></section>
<section className="faq" id="faq"><div><div className="kicker">QUESTIONS</div><h2>THE <i>DETAILS.</i></h2></div><div className="faqlist">{faqs.map((f,i)=><button key={f[0]} onClick={()=>setOpen(open===i?-1:i)}><div><strong>{f[0]}</strong><Plus className={open===i?'rot':''}/></div>{open===i&&<p>{f[1]}</p>}</button>)}</div></section>
<section className="join" id="join"><div className="glow"/><div className="kicker">K4K ACADEMY MEMBERSHIP</div><h2>YOUR NEXT VIDEO<br/>STARTS <i>HERE.</i></h2><p>Learn the method. Build the skill. Keep evolving.</p><LocalPrice/><div className="joinchecks">{['Full lesson library','New prompt drops','New video tutorials','Future updates'].map(x=><span key={x}><Check/> {x}</span>)}</div><CTA/><small><LockKeyhole/> Secure Stripe subscription checkout.</small></section>
<footer><div className="brand"><span>K4K</span> ACADEMY</div><p>CREATE. DIRECT. EVOLVE.</p><div>© 2026 KREATIVE STUDIOS 4K</div></footer>
</main>}