'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Check,Copy,Download,LockKeyhole,Play,Sparkles} from 'lucide-react';

const offers={GBP:{label:'£9.99',url:'https://buy.stripe.com/dRmbJ293u6d7egQ8CseEo0n'},BRL:{label:'R$44,99',url:'https://buy.stripe.com/dRmbJ293u6d7egQ8CseEo0n'},USD:{label:'$12.99',url:'https://buy.stripe.com/dRmbJ293u6d7egQ8CseEo0n'},EUR:{label:'€11.99',url:'https://buy.stripe.com/dRmbJ293u6d7egQ8CseEo0n'}};
const characterPrompt=`Using the uploaded person as the sole identity reference, create a professional character reference sheet while preserving facial structure, skin tone, hairstyle, body proportions and distinctive physical characteristics. Show consistent front, back, profile, three-quarter, full-body and close facial views. Maintain the same identity and wardrobe across every panel. Neutral studio background, even lighting and realistic proportions. Do not invent facial features or accessories.`;
const genjutsuPrompt=`Use the uploaded video as the primary motion, performance, composition and camera reference. Replace only the designated principal character with the person shown in the supplied character reference. Preserve facial identity, hairstyle, skin tone, body proportions and wardrobe consistently. Match the original movement, gestures, timing, orientation and interactions. Preserve handheld camera motion, framing, perspective, scene timing, environment, lighting and background people. Avoid identity drift, duplicate characters, warped hands, altered clothing or unnecessary camera changes.`;
function useOffer(){const[o,setO]=useState(offers.USD);useEffect(()=>{fetch('/api/market').then(r=>r.json()).then(x=>setO(offers[x.currency]||offers.USD)).catch(()=>{})},[]);return o}
function Copy({title,text}){const[c,setC]=useState(false);return <article className="promptCard"><small>READY TO USE</small><h3>{title}</h3><pre>{text}</pre><button onClick={async()=>{await navigator.clipboard.writeText(text);setC(true);setTimeout(()=>setC(false),1400)}}><Copy size={15}/>{c?'COPIED':'COPY PROMPT'}</button></article>}
export default function Home(){const o=useOffer();return <main className="launchPage">
<nav><a className="brand" href="#top"><span>K4K</span> ACADEMY</a><a className="loginLink" href="/login">Member Login</a></nav>
<section className="launchHero" id="top"><div className="eyebrow"><Sparkles size={14}/> DAILY AI TUTORIAL MEMBERSHIP</div><h1>WATCH IT.<br/><em>RECREATE IT.</em></h1><p>Learn the exact AI workflow behind viral creator videos. Watch the tutorial, copy the prompts, download the lesson assets and build your own version.</p><div className="launchPrice"><strong>{o.label}</strong><span>/ MONTH</span></div><a className="btn" href={o.url}>JOIN K4K ACADEMY <ArrowRight/></a><div className="micro"><span><Check/> New tutorials daily</span><span><Check/> Copy-ready prompts</span><span><Check/> Downloadable resources</span></div></section>

<section className="homeCase"><div className="kicker">FEATURED WORKFLOW 001</div><h2>HOW I RECREATED A VIRAL VIDEO <i>WITH AI.</i></h2><p className="caseLead">See the reference and AI result first, then follow the exact process below.</p><div className="homeVideos"><article><div className="homeVideo"><Play/><span>ORIGINAL VIDEO</span></div><h3>Reference Video</h3><p>The movement, performance and camera reference.</p></article><article><div className="homeVideo"><Play/><span>AI VERSION</span></div><h3>AI Recreation</h3><p>Created using a character sheet and <b>Genjutsu inside Higgsfield</b>.</p></article></div><div className="workflowStats"><span><b>3.7M</b> views / 24h</span><span><b>241K</b> likes</span><span><b>2,103</b> comments</span><span><b>73K</b> shares</span><span><b>14K</b> saves</span></div></section>

<section className="simpleSteps"><div className="kicker">THE WORKFLOW</div><h2>REFERENCE → CHARACTER → <i>HIGGSFIELD GENJUTSU.</i></h2><div className="simpleGrid"><article><b>01</b><h3>Choose the reference</h3><p>Use footage with movement, timing and camera energy you want to recreate.</p></article><article><b>02</b><h3>Create your character sheet</h3><p>Lock face, hair, proportions and wardrobe before generating.</p></article><article><b>03</b><h3>Open Genjutsu on Higgsfield</h3><p>Upload the reference video and character sheet, choose Motion Transfer, paste the K4K prompt and generate.</p></article></div>
<Copy title="Character Sheet Prompt" text={characterPrompt}/><Copy title="Higgsfield Genjutsu Prompt" text={genjutsuPrompt}/>
<div className="resourceStrip"><div><small>LESSON RESOURCE</small><h2>Reference video</h2><p>Members can download the authorised reference asset and practise this workflow.</p></div><button disabled><Download/> DOWNLOAD REFERENCE VIDEO</button></div></section>

<section className="launchJoin"><div className="kicker">K4K ACADEMY</div><h2>ONE MEMBERSHIP.<br/><i>NEW AI WORKFLOWS DAILY.</i></h2><p>Video tutorials, exact prompts and practical creator workflows in one place.</p><div className="launchPrice"><strong>{o.label}</strong><span>/ MONTH</span></div><a className="btn" href={o.url}>START LEARNING <ArrowRight/></a><small><LockKeyhole/> Secure subscription checkout.</small></section>
<footer><div className="brand"><span>K4K</span> ACADEMY</div><p>CREATE. DIRECT. EVOLVE.</p><div>© 2026 KREATIVE STUDIOS 4K</div></footer>
</main>}